version: '3.7'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev', '--debug', '--import-realm', '--features=client-policies']
    ports:
      - 8080:8080
      - 8443:8443
      - 8787:8787
    volumes:
      - ./target/keycloak-add-request-header-claim.jar:/opt/keycloak/providers/keycloak-add-request-header-claim.jar
  keycloak-spi-builder:
    image: maven:3.8.4-openjdk-17 
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: mvn clean install