name: Package Release

on:
  push:
    tags:
      - '*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')" >> $GITHUB_ENV
      shell: bash

    - name: Create Release
      run: gh release create $VERSION target/*.jar --title "Release $VERSION" --notes "Release $VERSION"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: keycloak-custom-form-param-mapper-${{ env.VERSION }}
        path: target/*.jar
